{% set version = "0.1.0" %}

package:
  name: mlmcpy
  version: {{ version }}

source:
  git_url: https://github.com/nasa/MLMCPy.git

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy

about:
  home: https://github.com/nasa/MLMCPy
  license: APACHE
  license_file: LICENSE
  summary: 'MLMCPy is an open source Python implementation of the Multi-Level Monte Carlo (MLMC) method for uncertainty propagation.'
  doc_source_url: https://github.com/nasa/MLMCPy/blob/master/README.md